$ANSIBLE_VAULT;1.1;AES256
36303836373566323262653135376239383739383535643939646138363765663533633337663665
6134643433643030346539346232656261383961646266360a623435646537326237386163333238
38613039666162366332643061643465613964316661633035656332306433323036643533616231
3164653630376330630a663564316634306262663534363838333365363166396562646231666436
34303965396533366534353535313133643638353934653339313038343032656437356464663932
39303464333631363230313730363937326632363361343437616436623663663934643263653066
35383636313939373830663762663330643437333062343763346638326334306232333839646239
61666537396362613438383933643162326161383765316332653366653032656133633061313766
37363536373939353538636264383039386137663034633565636365653934646132636164623835
38346437643162303437656233646230653431386134613835323030333234643966393161393534
62393338623139653937383662626334623235323162646166313139643538643930396137646264
36323236303762356233623265643661653333633539626166636335346561323561376334613362
35386236613164643131333237633737393061326636333830326266333737346365
